### ISSUE TITLE
[Question] User data

### ISSUE THREAD

**Issue by iBicha** [keijiro/TextureUpdateExample#1]
Is there a way to pass a pointer to the callback? It would be more convenient, so that a pointer can holder the data to upload.

Tried casting to uint (which shouldn't be done in the first place) even if it worked on Android, it failed on iOS.

**Comment by keijiro** [comment]
I can understand you (in some cases I wanted to give data to a plugin via a pointer too), but casting between uint and `void*` doesn't work on 64-bit architectures. You have to implement a data registry or something like that to transfer data with uint ID.

**Comment by iBicha** [comment]
That's what I ended up doing, sort of a lookup table to get pointers by index.
How can I send feedback to Unity?
Thank you

**Comment by keijiro** [comment]
Here is the feedback page https://feedback.unity3d.com
