### ISSUE TITLE
how to mac plugin do 

### ISSUE THREAD

**Issue by lihongyi1234** [keijiro/TextureUpdateExample#10]
it's great i see your project, now I need to do a project with MacOS, do you use metal in mac? or opengl ES? I need to use metal. another problem is that how to copy texture in plugin in mac,looking forward to your reply

**Comment by keijiro** [comment]
>  do you use metal in Mac?

Yes, it's Metal.

> how to copy texture in plugin in Mac

See the sample.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by lihongyi1234** [comment]
I see your Plasma.c file, it is just a memepy copy process, if i have id<MTLTExture> texture in mac，how can I copy to unity in plugin. another question, if i have MTLTexture  in GPU ,how can i copy it to unity?

**Comment by keijiro** [comment]
Then this project is not a solution for your problem. I'd recommend using Unity forum or other communities to solve your problem. Please understand that this issue tracker is dedicated to this specific project.

**Comment by lihongyi1234** [comment]
ok ,thank you very much
