### ISSUE TITLE
render api agnostic too? 

### ISSUE THREAD

**Issue by jurasans** [keijiro/TextureUpdateExample#3]
hi
in the unity docs i see that usually you need some kind of 
"OnGraphicsDeviceEvent" handler to register the graphics api

i see that in your code there is non..
is that because you didnt include your own graphics interface or because unity has done one "behind the scenes" and now we developers dont need all that boiler plate code in recent unity releases? :)

**Comment by keijiro** [comment]
The CustomTextureUpdate callback is different from the low-level native plugin.

My understanding is that you have to implement `OnGraphicsDeviceEvent` and other things to access the low-level graphics API from native code, so it's celled "low-level native plugin". The CustomTextureUpdate callback is not under this umbrella. It's a platform/API agnostic interface to update managed textures from the C++ side without worrying about graphic APIs.
