### ISSUE TITLE
[Question not issue] What is this good for?

### ISSUE THREAD

**Issue by foxnoodles** [keijiro/TextureUpdateExample#5]
Hi Keijiro San,

Could you please explain what's the best use case scenario for this approach? I mean why would I need to update textures via my own custom plugin?

**Comment by keijiro** [comment]
This is useful when you want to use C/C++/asm to update textures. There might be some motives on it. For example:

- You prefer C++ over C#.
- It needs to be heavily optimized with C/C++/asm.
- You want to use a 3rd party library with C++.

[KlakNDI](https://github.com/keijiro/KlakNDI) is a good example of the third reason. Thanks to the TextureUpdate callback, it can update textures with received video streams without adding extra costs.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
